language: scala
scala:
- 2.11.2
- 2.10.4
jdk:
- oraclejdk7
install:
- ./.travis-cache.sh
script:
- sbt ++$TRAVIS_SCALA_VERSION -no-share --warn compile test:compile it:compile
- sbt ++$TRAVIS_SCALA_VERSION -no-share test
- sbt ++$TRAVIS_SCALA_VERSION -no-share it:test
- sbt ++$TRAVIS_SCALA_VERSION -no-share --warn unidoc
notifications:
  flowdock:
    secure: HiRg1CHYiKftvGCfbOWmWeg1RSFctfnc3hRc4xdv8wH5OVzGyXk7UgBh8/EPIdbs4cL0HU2Lv1q+l3ukFKx/YDAwTNmuad5sC8wvhvjWNxpBDz+4IYcgcraRSXWElRgM2MugPgmsinPpAr8Ma1GLlNNBUVnzquUW6PA2XOAkSkg=
