#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Datomisca

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://dwhjames.github.io/datomisca"

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/datomisca"


navigation:
- title: Home
  url: index.html
- title: Releases
  url: doc/releases.html
- title: Philosophy
  url: doc/philosophy.html
- title: Features in Detail
  url: doc/features.html
- title: Getting Started
  url: doc/getstarted.html
- title: Building transaction data
  url: doc/txdata.html
- title: Type safety with type classes
  url: doc/typeclasses.html
- title: Datomisca for Play Framework
  url: doc/play-datomisca.html
- title: About Us
  url: doc/about-us.html

latestrelease: 0.7-RC1

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
