safe: false
pygments: true
lsi: false
baseurl: /datomisca
markdown: redcarpet
navigation:
- title: Home
  url: index.html
- title: Releases
  url: doc/releases.html
- title: Philosophy
  url: doc/philosophy.html
- title: Features in Detail
  url: doc/features.html
- title: Getting Started
  url: doc/getstarted.html
- title: Datomisca for Play Framework
  url: doc/play-datomisca.html
- title: About Us
  url: doc/about-us.html
